config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :tweets

  post 'tweets/follow' => 'tweets#follow'

root to: 'tweets#index'
  # For details on the  DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follower, class_name: "User"

  def self.save_follow(id)
    self.create(follower_id: id, user_id: id)
  end
  
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets
  has_many :followers, :class_name => "Relationship", :foreign_key => "user_id"
  has_many :following, :class_name => "Relationship", :foreign_key => "follower_id"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
   skip_before_action :verify_authenticity_token  

  def index
    @tweets = Tweet.all
  
  end
  
  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(tweet_params)
    user_id= params[:tweet][:user_id]
    if tweet.save
      tweet.update_attribute(:user_id, user_id)
      redirect_to tweets_path
    else
      render 'new'
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def follow
    Relationship.save_follow(params[:id])
  end
  
  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweets_path
    else
      render 'edit'
    end
  end
 
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
 
    redirect_to tweets_path
  end
  
  private
  def tweet_params
    params.require(:tweet).permit(:user_id, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>

   <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="pull-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>
  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<h1>New Tweet Form</h1>
<%= form_for (@tweet) do |f| %>
  <%= f.hidden_field  :user_id, value:current_user.id %>

  <%= f.label :content %>
  <%= f.text_field :content %>
  <br><br>
  
  <%= f.submit %>
<% end %>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', tweet_path %>

app/views/tweets/index.html.erb
<% if user_signed_in?%>
<div style="margin-left:548px;">
  <%= hidden_field_tag :user_id, current_user.id%>
  <% logger.info "gshdghsfh #{current_user.inspect}"%>
<%= link_to 'New Tweet', new_tweet_path %>
  </div>
<div class="container">
  <div class="row">
    <div class="col-sm-6" style="border-color: #666666">
      <% @tweets.each do |tweet| %>
        <strong><%= tweet.user.email %></strong>
        <%= tweet.created_at.strftime("%d %b %Y at %I:%M %p") %>
        <% if current_user.tweets.include?(tweet)%>
                <p><%= tweet.content%>
        <%= link_to 'edit', edit_tweet_path(tweet) %>
        <%= link_to 'Delete', tweet_path(tweet), method: :delete,
              data: { confirm: 'Are you sure?' } %></p>
              <% else %>
              <p><%= tweet.content%></p>
                      <button type="button" id="follow-button" class="foloow">Follow</button>
              <% end %>

        <br><br>
      <% end %>
    </div>
  </div>
</div>
<% else %>
<% redirects_to new_user_session_path%>
<% end %>

<script>
$(document).ready(function() {
$("#follow-button").click(function(){
  var $this = $(this);
    $this.toggleClass('foloow');
    if($this.hasClass('foloow')){
        $this.text('Follow');         
    } else {
        $this.text('Unfollow');
    }
  id = $('#user_id').val();
    $.ajax({
      type: "POST",
      url: "tweets/follow",
      data_type :'JSON',
      data: {
        id: id
      },
      success: function(data) {
        alert('ok');
      },
      error: function(data) {
        alert('error');
      }
    });
    });
});
</script>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<h1>Profile Page for <%= @tweet.id %></h1>

<p><%= @tweet.content %></p>